project:
  type: website
  output-dir: docs

website:
  title: "Aysu Soylu's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/emu-hacettepe-analytics/emu430-fall2024-aysusoylu
     
      - icon: linkedin
        href: https://www.linkedin.com/in/aysu-soylu-81551a254?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bsv8zlW1gRxGn8%2FJgduakhg%3D%3D

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU430 - 2024 Fall" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: pulse 
      dark: superhero
    css: styles.css


editor: visual

